name: fetch-metrics

permissions:
  contents: write

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  stats:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          committer_branch: metrics
          committer_message: "build: update `${filename}`"

          user: rhynl
          template: classic
          base: header, activity, community
          config_timezone: America/Montevideo

  achievements:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          committer_branch: metrics
          committer_message: "build: update `${filename}`"

          user: rhynl
          template: classic
          base: ""
          config_display: large
          config_timezone: America/Montevideo
          config_output: svg
          filename: achievements.svg
          repositories_batch: 5

          plugin_achievements: yes
          plugin_achievements_threshold: C
          plugin_achievements_secrets: yes
          plugin_achievements_display: compact

  blog_updates:
    runs-on: ubuntu-latest
    name: RSS
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          committer_branch: metrics
          committer_message: "build: update `${filename}`"

          base: ""
          config_output: svg
          filename: posts.svg

          plugin_rss: yes
          plugin_rss_source: https://rhynl.dev/rss.xml
          plugin_rss_limit: 4
