name: fetch-metrics

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  stats:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@v3.33
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          committer_branch: metrics
          committer_message: "build: update `${filename}`"

          # Options
          user: rhynl
          template: classic
          base: header, activity, community
          config_timezone: America/Montevideo

  notable:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@v3.33
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          committer_branch: metrics
          committer_message: "build: update `${filename}`"

          # Options
          user: rhynl
          template: classic
          base: ""
          config_display: large
          config_timezone: America/Montevideo
          config_output: svg
          config_padding: 0, 30
          filename: notable.svg

          # Notable contributions
          plugin_notable: yes
          plugin_notable_filter: stars:>25

  notable2:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@v3.33
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          committer_branch: metrics
          committer_message: "build: update `${filename}`"

          # Options
          user: rhynl
          template: classic
          base: ""
          config_display: large
          config_timezone: America/Montevideo
          config_output: svg
          config_padding: 0, 30
          filename: notable2.svg

          # Notable contributions
          plugin_notable: yes
          plugin_notable_filter: stars:>25
          plugin_notable_indepth: yes
          plugin_notable_repositories: yes
          plugin_notable_from: all

  achievements:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@v3.33
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          committer_branch: metrics
          committer_message: "build: update `${filename}`"

          # Options
          user: rhynl
          template: classic
          base: ""
          config_display: large
          config_timezone: America/Montevideo
          config_output: svg
          filename: achievements.svg
          repositories_batch: 5

          # Achievement plugin
          plugin_achievements: yes
          plugin_achievements_threshold: C
          plugin_achievements_secrets: yes
          plugin_achievements_display: compact
